name: trabalho_final
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  file_picker: ^8.1.2
  image_picker: ^1.0.7
  month_picker_dialog: ^2.0.3
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter:
    sdk: flutter
  intl: ^0.18.1
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
